title: "Nir Blog"
description: "Un espace pour partager les connaissances"
baseurl: "/Nir-Blog"
url: "https://nirtoolsbox.github.io"
theme: minima
permalink: /:year/:month/:title/
collections:
  posts:
    output: true
    permalink: /:year/:month/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true